# Generated by Django 4.1.2 on 2022-10-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='native_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_no',
        ),
    ]
